# Análisis con NumPy

Este notebook contiene ejemplos básicos y útiles para manipular arrays con NumPy. Aprenderás a crear arrays, acceder a sus elementos, hacer operaciones matemáticas y usar funciones útiles.


In [2]:
import numpy as np

print("NumPy import successful!")
print("NumPy version:", np.__version__)


NumPy import successful!
NumPy version: 2.2.5


## Crear arrays

Usamos `np.array()` para convertir listas o listas de listas en arrays de NumPy.

In [ ]:
# Array 1D
arr1d = np.array([1, 2, 3, 4])
print("Array 1D:", arr1d)
print("Form:", arr1d.shape, "| Dimensions:", arr1d.ndim)

# Array 2D (matriz)
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\nArray 2D:\n", arr2d)
print("Form:", arr2d.shape, "| Dimensions:", arr2d.ndim)


Array 1D: [1 2 3 4]
Forma: (4,) | Dimensiones: 1

Array 2D:
 [[1 2 3]
 [4 5 6]]
Forma: (2, 3) | Dimensiones: 2


## Arrays especiales

NumPy tiene funciones para crear arrays con ceros, unos, rangos, etc.

In [5]:
zeros = np.zeros((2, 3))
ones = np.ones(4)
rango = np.arange(0, 10, 2)

print("Array of zeros (2x3):\n", zeros)
print("Array of ones:", ones)
print("Array with arange:", rango)


Array of zeros (2x3):
 [[0. 0. 0.]
 [0. 0. 0.]]
Array of ones: [1. 1. 1. 1.]
Array with arange: [0 2 4 6 8]


## Basic Operations

We can add, subtract, multiply arrays, or apply mathematical functions easily.


In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Sum:", a + b)
print("Multiplication by scalar:", a * 2)
print("Square root:", np.sqrt(a))
print("Sine:", np.sin(a))


Sum: [5 7 9]
Multiplication by scalar: [2 4 6]
Square root: [1.         1.41421356 1.73205081]
Sine: [0.84147098 0.90929743 0.14112001]


## Indexing and Slicing

We can access individual elements or subsets of arrays.


In [7]:
print("First element of a:", a[0])
print("Last two elements of b:", b[-2:])

print("Element (0, 1) of arr2d:", arr2d[0, 1])
print("First row of arr2d:", arr2d[0])
print("Second column of arr2d:", arr2d[:, 1])


First element of a: 1
Last two elements of b: [5 6]
Element (0, 1) of arr2d: 2
First row of arr2d: [1 2 3]
Second column of arr2d: [2 5]


## Quick Statistics

NumPy allows calculating sums, means, standard deviations, and more.


In [8]:
print("Total sum of arr2d:", np.sum(arr2d))
print("Mean by column:", np.mean(arr2d, axis=0))
print("Maximum by row:", np.max(arr2d, axis=1))


Total sum of arr2d: 21
Mean by column: [2.5 3.5 4.5]
Maximum by row: [3 6]
